Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(figsize=(15, 6), constrained_layout=True)
gs = fig.add_gridspec(nrows=2, height_ratios=[1.25, 2])
gs1 = gs[0].subgridspec(1, 2, width_ratios=[1, 3],wspace=0.3)
gs2 = gs[1].subgridspec(ncols=3, nrows=1,wspace=0.3)
plt.rcParams.update({'font.size': 10})

a1 = fig.add_subplot(gs1[0])
a2 = fig.add_subplot(gs1[1])
a3 = fig.add_subplot(gs2[0])
a4 = fig.add_subplot(gs2[1])
a5 = fig.add_subplot(gs2[2])
for a in [a1,a2,a3,a4,a5]:
    change_style(a)
fig.subplots_adjust(hspace=0.4)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [11][0m, in [0;36m<cell line: 12>[0;34m()[0m
[1;32m     11[0m a5 [38;5;241m=[39m fig[38;5;241m.[39madd_subplot(gs2[[38;5;241m2[39m])
[1;32m     12[0m [38;5;28;01mfor[39;00m a [38;5;129;01min[39;00m [a1,a2,a3,a4,a5]:
[0;32m---> 13[0m     [43mchange_style[49m[43m([49m[43ma[49m[43m)[49m
[1;32m     14[0m fig[38;5;241m.[39msubplots_adjust(hspace[38;5;241m=[39m[38;5;241m0.4[39m)

Input [0;32mIn [10][0m, in [0;36mchange_style[0;34m(ax, xlim, ylim, xlabel, ylabel)[0m
[1;32m      4[0m ax[38;5;241m.[39mset_ylabel(ylabel)
[1;32m      6[0m ax[38;5;241m.[39mgrid(linestyle[38;5;241m=[39m[38;5;124m"[39m[38;5;124m--[39m[38;5;124m"[39m, linewidth[38;5;241m=[39m[38;5;241m0.5[39m, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124m.25[39m[38;5;124m'[39m, zorder[38;5;241m=[39m[38;5;241m-[39m[38;5;241m10[39m)
[0;32m----> 8[0m [38;5;28;01mif[39;00m [43mylim[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [[38;5;28;01mNone[39;00m]:
[1;32m      9[0m     ax[38;5;241m.[39mset_ylim([38;5;241m*[39mylim)
[1;32m     10[0m [38;5;28;01mif[39;00m xlim[[38;5;241m0[39m] [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [[38;5;28;01mNone[39;00m]:

[0;31mTypeError[0m: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable

